require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PingsController do

  # This should return the minimal set of attributes required to create a valid
  # Ping. As you add validations to Ping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "http_code" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pings as @pings" do
      ping = Ping.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pings).should eq([ping])
    end
  end

  describe "GET show" do
    it "assigns the requested ping as @ping" do
      ping = Ping.create! valid_attributes
      get :show, {:id => ping.to_param}, valid_session
      assigns(:ping).should eq(ping)
    end
  end

  describe "GET new" do
    it "assigns a new ping as @ping" do
      get :new, {}, valid_session
      assigns(:ping).should be_a_new(Ping)
    end
  end

  describe "GET edit" do
    it "assigns the requested ping as @ping" do
      ping = Ping.create! valid_attributes
      get :edit, {:id => ping.to_param}, valid_session
      assigns(:ping).should eq(ping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ping" do
        expect {
          post :create, {:ping => valid_attributes}, valid_session
        }.to change(Ping, :count).by(1)
      end

      it "assigns a newly created ping as @ping" do
        post :create, {:ping => valid_attributes}, valid_session
        assigns(:ping).should be_a(Ping)
        assigns(:ping).should be_persisted
      end

      it "redirects to the created ping" do
        post :create, {:ping => valid_attributes}, valid_session
        response.should redirect_to(Ping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ping as @ping" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ping.any_instance.stub(:save).and_return(false)
        post :create, {:ping => { "http_code" => "invalid value" }}, valid_session
        assigns(:ping).should be_a_new(Ping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ping.any_instance.stub(:save).and_return(false)
        post :create, {:ping => { "http_code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ping" do
        ping = Ping.create! valid_attributes
        # Assuming there are no other pings in the database, this
        # specifies that the Ping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ping.any_instance.should_receive(:update).with({ "http_code" => "" })
        put :update, {:id => ping.to_param, :ping => { "http_code" => "" }}, valid_session
      end

      it "assigns the requested ping as @ping" do
        ping = Ping.create! valid_attributes
        put :update, {:id => ping.to_param, :ping => valid_attributes}, valid_session
        assigns(:ping).should eq(ping)
      end

      it "redirects to the ping" do
        ping = Ping.create! valid_attributes
        put :update, {:id => ping.to_param, :ping => valid_attributes}, valid_session
        response.should redirect_to(ping)
      end
    end

    describe "with invalid params" do
      it "assigns the ping as @ping" do
        ping = Ping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ping.any_instance.stub(:save).and_return(false)
        put :update, {:id => ping.to_param, :ping => { "http_code" => "invalid value" }}, valid_session
        assigns(:ping).should eq(ping)
      end

      it "re-renders the 'edit' template" do
        ping = Ping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ping.any_instance.stub(:save).and_return(false)
        put :update, {:id => ping.to_param, :ping => { "http_code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ping" do
      ping = Ping.create! valid_attributes
      expect {
        delete :destroy, {:id => ping.to_param}, valid_session
      }.to change(Ping, :count).by(-1)
    end

    it "redirects to the pings list" do
      ping = Ping.create! valid_attributes
      delete :destroy, {:id => ping.to_param}, valid_session
      response.should redirect_to(pings_url)
    end
  end

end
