require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScheduledsController do

  # This should return the minimal set of attributes required to create a valid
  # Scheduled. As you add validations to Scheduled, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "hour" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScheduledsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all scheduleds as @scheduleds" do
      scheduled = Scheduled.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scheduleds).should eq([scheduled])
    end
  end

  describe "GET show" do
    it "assigns the requested scheduled as @scheduled" do
      scheduled = Scheduled.create! valid_attributes
      get :show, {:id => scheduled.to_param}, valid_session
      assigns(:scheduled).should eq(scheduled)
    end
  end

  describe "GET new" do
    it "assigns a new scheduled as @scheduled" do
      get :new, {}, valid_session
      assigns(:scheduled).should be_a_new(Scheduled)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheduled as @scheduled" do
      scheduled = Scheduled.create! valid_attributes
      get :edit, {:id => scheduled.to_param}, valid_session
      assigns(:scheduled).should eq(scheduled)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Scheduled" do
        expect {
          post :create, {:scheduled => valid_attributes}, valid_session
        }.to change(Scheduled, :count).by(1)
      end

      it "assigns a newly created scheduled as @scheduled" do
        post :create, {:scheduled => valid_attributes}, valid_session
        assigns(:scheduled).should be_a(Scheduled)
        assigns(:scheduled).should be_persisted
      end

      it "redirects to the created scheduled" do
        post :create, {:scheduled => valid_attributes}, valid_session
        response.should redirect_to(Scheduled.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheduled as @scheduled" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scheduled.any_instance.stub(:save).and_return(false)
        post :create, {:scheduled => { "hour" => "invalid value" }}, valid_session
        assigns(:scheduled).should be_a_new(Scheduled)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scheduled.any_instance.stub(:save).and_return(false)
        post :create, {:scheduled => { "hour" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheduled" do
        scheduled = Scheduled.create! valid_attributes
        # Assuming there are no other scheduleds in the database, this
        # specifies that the Scheduled created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Scheduled.any_instance.should_receive(:update).with({ "hour" => "" })
        put :update, {:id => scheduled.to_param, :scheduled => { "hour" => "" }}, valid_session
      end

      it "assigns the requested scheduled as @scheduled" do
        scheduled = Scheduled.create! valid_attributes
        put :update, {:id => scheduled.to_param, :scheduled => valid_attributes}, valid_session
        assigns(:scheduled).should eq(scheduled)
      end

      it "redirects to the scheduled" do
        scheduled = Scheduled.create! valid_attributes
        put :update, {:id => scheduled.to_param, :scheduled => valid_attributes}, valid_session
        response.should redirect_to(scheduled)
      end
    end

    describe "with invalid params" do
      it "assigns the scheduled as @scheduled" do
        scheduled = Scheduled.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scheduled.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheduled.to_param, :scheduled => { "hour" => "invalid value" }}, valid_session
        assigns(:scheduled).should eq(scheduled)
      end

      it "re-renders the 'edit' template" do
        scheduled = Scheduled.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scheduled.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheduled.to_param, :scheduled => { "hour" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheduled" do
      scheduled = Scheduled.create! valid_attributes
      expect {
        delete :destroy, {:id => scheduled.to_param}, valid_session
      }.to change(Scheduled, :count).by(-1)
    end

    it "redirects to the scheduleds list" do
      scheduled = Scheduled.create! valid_attributes
      delete :destroy, {:id => scheduled.to_param}, valid_session
      response.should redirect_to(scheduleds_url)
    end
  end

end
